server:
  servlet:
    context-path: /springboot  # 根路径，必须是/开头的
  port: 8088
logging:
  level:
    com.aaa.dao : debug #控制台打印sql語句
spring:
  datasource:  # 数据库配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/roundabout?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: admin
  thymeleaf:
    # encoding: UTF-8
    # prefix: classpath:/templates/
    # suffix: .html
    mode: HTML5  # 视图模型
    cache: false # 模板缓存

  resources:
    static-locations: classpath:/META- INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/ # 静态资源路径

mybatis:
  type-aliases-package: com.aaa.entity
  mapper-locations: classpath:mapper/*.xml
